### ISSUE TITLE
"Cannot encode parameter of type" for enum fields when using @Modifying @Query

### ISSUE THREAD

**Issue by eau-de-la-seine** [spring-projects/spring-data-r2dbc#271]
Hi, I've noticed that my entity object with enum fields are correctly inserted into the table when I use the `ReactiveCrudRepository#save()` method... but it doesn't work when I'm creating a `@Modifying @Query("UPDATE request")` abstract method with placeholders as method parameters in my ReactiveCrudRepository interface.

Stacktrace:
```
java.lang.IllegalArgumentException: Cannot encode parameter of type my.pack.MyEnum
	at io.r2dbc.h2.codecs.DefaultCodecs.encode(DefaultCodecs.java:73) ~[r2dbc-h2-0.8.1.RELEASE.jar:0.8.1.RELEASE]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ SQL "UPDATE
```

My dependencies:
```
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-r2dbc</artifactId>
			<version>1.0.0.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>io.r2dbc</groupId>
			<artifactId>r2dbc-h2</artifactId>
			<version>0.8.1.RELEASE</version>
		</dependency>
```

**Comment by mp911de** [comment]
Can you attach the repository and entity declaration for your repository?

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by michaelilyin** [comment]
I faced same issue. Problem not in entity but in passing enums as parameters of repository method:
```
  // language=PostgreSQL
  @Query("""
    UPDATE house_invites
    SET
      resolution_status = :resolution_status,
      resolution = :resolution,
      resolved_by = :updated_by,
      resolved_at = :updated_at
    WHERE
      id = :id
    RETURNING *
  """)
  @Modifying
  fun updateResolution(
    @Param("id") id: Long,
    @Param("resolution_status") resolutionStatus: InvitationResolution,
    @Param("resolution") resolution: String,
    @Param("updated_by") updatedBy: UUID,
    @Param("updated_at") updatedAt: LocalDateTime
  ): Mono<HouseInvitationEntity>
```

Repository declaration
```
@Repository
interface HouseInvitationRepository : ReactiveCrudRepository<HouseInvitationEntity, Long>
```

Entity declaration:
```
@Table("house_invites")
data class HouseInvitationEntity(
  @Id
  val id: Long?,
  val houseId: Long,
  val userEmail: String,
  val invitedBy: UUID,
  val invitedAt: LocalDateTime,
  val invitation: String,
  var resolutionStatus: InvitationResolution,
  var resolution: String?,
  var resolvedBy: UUID?,
  var resolvedAt: LocalDateTime?
): Pageable {
  override var _count: Int? = null
}
```

Enum declaration:
```
enum class InvitationResolution : NamedEnum {
  NEW,
  ACCEPTED,
  REJECTED,
  CANCELLED;
}
```

Also I tried to write custom converter for enum values, it successfully called for `save` calls but never called for above custom query.

**Comment by mp911de** [comment]
That issue was fixed with a newer release. Please upgrade to version 1.1.0.RELEASE.

**Comment by jehanzebqayyum** [comment]
Still getting the issue with latest version when for enum array which is nullable 
`Cannot encode null parameter of type [Lcom.deliveryhero.vms.dto.DeliveryType;`

**Comment by mp911de** [comment]
That's an enum-array. @jehanzebqayyum please file a new ticket along with a bit of code how you're using the repository method.
