### ISSUE TITLE
Spring-data IN clause is broken 

### ISSUE THREAD

**Issue by MarcTerrasson** [spring-projects/spring-data-r2dbc#534]
Spring-boot version : 2.4.0
r2dbc-postgresql : 0.8.6.RELEASE

Hello Everyone,

I have this issue when I try to retrieve data with IN clause.

```
java.lang.IllegalArgumentException: Cannot encode parameter of type java.util.ArrayList
	at io.r2dbc.postgresql.codec.DefaultCodecs.encode(DefaultCodecs.java:166)
	at io.r2dbc.postgresql.ExtendedQueryPostgresqlStatement.bind(ExtendedQueryPostgresqlStatement.java:90)
	at io.r2dbc.postgresql.ExtendedQueryPostgresqlStatement.bind(ExtendedQueryPostgresqlStatement.java:46)
	at org.springframework.r2dbc.core.DefaultDatabaseClient$DefaultGenericExecuteSpec.lambda$bindByIndex$6(DefaultDatabaseClient.java:442)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
```

Here is the query I use.

```
@Query("SELECT id_tpv FROM tpv_vehicule tv INNER JOIN vehicule v ON v.id = tv.id_vehicule WHERE tv.id_tpv IN $1 AND v.immatriculation = $2")
Flux<Long> filterTpvIdsByImmatriculation(List<Long> tpvIds, String immatriculation);
```

This issue is really similar to this one https://github.com/spring-projects/spring-data-r2dbc/issues/361
But it should be fixed in the 2.4.0.

**Comment by mp911de** [comment]
This works as expected. Using native bind markers (`$1`, `$2`, `$…`) binds values directly to the statement without further conversion. SQL doesn't understand collections to be expanded for certain operators. Your query must either:

1. Provide the number of bind markers corresponding to the desired amount of `IN` elements (`WHERE … IN ($1, $2, $…)`)
2. Make use of named parameters. With named parameters, Spring pre-processes the SQL and is able to rewrite it including collection expansion.

Your query would look like this: 

```
SELECT id_tpv FROM tpv_vehicule tv INNER JOIN vehicule v ON v.id = tv.id_vehicule WHERE tv.id_tpv IN : tpvIds AND v.immatriculation = : immatriculation
```

**Comment by MarcTerrasson** [comment]
I tried and it didn't work : 

```
ERROR [reactor-tcp-epoll-1] reactor.util.Loggers$Slf4JLogger: 
java.lang.UnsupportedOperationException: Binding parameters is not supported for the statement 'SELECT id_tpv FROM tpv_vehicule tv INNER JOIN vehicule v ON v.id = tv.id_vehicule WHERE tv.id_tpv IN : tpvIds AND v.immatriculation = : immatriculation'
	at io.r2dbc.postgresql.SimpleQueryPostgresqlStatement.bind(SimpleQueryPostgresqlStatement.java:78)
	at io.r2dbc.postgresql.SimpleQueryPostgresqlStatement.bind(SimpleQueryPostgresqlStatement.java:44)
	at org.springframework.r2dbc.core.DefaultDatabaseClient$DefaultGenericExecuteSpec.lambda$bindByIndex$6(DefaultDatabaseClient.java:442)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
```

**Comment by mp911de** [comment]
Note the space between `:` and `tpvIds`. Same for the second parameter. For some reason, the same space sneaked into my previous comment. I've fixed that in the comment above.

**Comment by MarcTerrasson** [comment]
Ho right, my bad. I tried and still have an error on the IN clause : 

```
2021-02-08 14:19:24,516 WARN  [reactor-tcp-epoll-1] reactor.util.Loggers$Slf4JLogger: Error: SEVERITY_LOCALIZED=ERROR, SEVERITY_NON_LOCALIZED=ERROR, CODE=42601, MESSAGE=syntax error at or near "$1", POSITION=102, FILE=scan.l, LINE=1149, ROUTINE=scanner_yyerror
2021-02-08 14:19:24,526 ERROR [reactor-tcp-epoll-1] reactor.util.Loggers$Slf4JLogger: | onError(org.springframework.r2dbc.BadSqlGrammarException: executeMany; bad SQL grammar [SELECT id_tpv FROM tpv_vehicule tv INNER JOIN vehicule v ON v.id = tv.id_vehicule WHERE tv.id_tpv IN :tpvIds AND v.immatriculation = :immatriculation]; nested exception is io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: [42601] syntax error at or near "$1")
2021-02-08 14:19:24,530 ERROR [reactor-tcp-epoll-1] reactor.util.Loggers$Slf4JLogger: 
org.springframework.r2dbc.BadSqlGrammarException: executeMany; bad SQL grammar [SELECT id_tpv FROM tpv_vehicule tv INNER JOIN vehicule v ON v.id = tv.id_vehicule WHERE tv.id_tpv IN :tpvIds AND v.immatriculation = :immatriculation]; nested exception is io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: [42601] syntax error at or near "$1"
	at org.springframework.r2dbc.connection.ConnectionFactoryUtils.convertR2dbcException(ConnectionFactoryUtils.java:235)
	at org.springframework.r2dbc.core.DefaultDatabaseClient.lambda$inConnectionMany$8(DefaultDatabaseClient.java:147)
	at reactor.core.publisher.Flux.lambda$onErrorMap$28(Flux.java:6579)
	at reactor.core.publisher.Flux.lambda$onErrorResume$29(Flux.java:6632)
```

**Comment by mp911de** [comment]
I think you need to add braces around the parameters. Sorry for the hassle. See https://github.com/spring-projects/spring-data-r2dbc/blob/b28a24e003538075cb44c5749edcd922f4b4050e/src/test/java/org/springframework/data/r2dbc/core/NamedParameterUtilsUnitTests.java#L343 for further reference.

**Comment by MarcTerrasson** [comment]
Nice, that works !
Many thanks for your time.
